version: '3.7'

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=PathodrugDB
    expose:
      - 8080
  
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.31
    restart: always
    command: 
      - '--local-infile=1'
      - '--secure-file-priv=docker-entrypoint-initdb.d'
    environment:
        MYSQL_ROOT_PASSWORD: sdl_sql2
        MYSQL_DATABASE: PathodrugDB
    ports:
        - "3308:3306"
    volumes:
      - ./mysqldb/init.sql:/docker-entrypoint-initdb.d/init.sql:rw
      - ./mysqldb/init_data:/docker-entrypoint-initdb.d/init_data:rw
